language: python
python:
- '2.7'
install:
- pip install awscli
script:
- echo "hello 1"
deploy:
  provider: s3
  region: us-east-2
  bucket: ts-test-brayest
  acl: 'private'
  on:
    repo: brayest/braytests
