language: python
python:
- '2.7'

env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH
    - AWS_DEFAULT_REGION=us-east-2

install:
- pip install awscli
script:
- echo "Initializing"

before_install:
  # Create folder with relevant files
  - mkdir -p ~/$TRAVIS_BUILD_NUMBER

jobs:
  include:
    - stage: Sync files
    - script: rsync -av --progress $TRAVIS_BUILD_DIR ~/$TRAVIS_BUILD_NUMBER --exclude .git --exclude README.md --exclude .travis.yml
    - stage: List objects
    - script: ls -la ~/$TRAVIS_BUILD_NUMBER
    - after_success:
        - echo "Sync Success"

after_success:
  - aws s3 sync ~/$TRAVIS_BUILD_NUMBER s3://ts-test-brayest/$TRAVIS_BUILD_NUMBER
