language: python
python:
- '2.7'

branches:
  except:
  - development

env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH
    - AWS_DEFAULT_REGION=us-east-2
    - VERSION=$TRAVIS_BUILD_NUMBER

install:
- pip install awscli

before_script:
  # Create folder with relevant files
  - mkdir -p ~/$TRAVIS_BUILD_NUMBER

jobs:
  include:
    - stage: MASTER
      # require the branch name to be master
      if: branch = master
      script: rsync -av --progress $TRAVIS_BUILD_DIR/ ~/$TRAVIS_BUILD_NUMBER/ --exclude .git --exclude README.md --exclude .travis.yml
    - stage: CLIENT
      # require the branch name to be master
      if: branch != master
      script: rsync -av --progress $TRAVIS_BUILD_DIR/ ~/$TRAVIS_BUILD_NUMBER/ --exclude .git --exclude README.md --exclude .travis.yml --exclude testmaster.txt


after_success:
  - aws s3 sync ~/$TRAVIS_BUILD_NUMBER s3://ts-test-brayest/$TRAVIS_BRANCH/$VERSION
